openapi: 3.0.1
info:
  title: Utility Payments
  version: 1.0.0
servers:
  - url: https://tenpo.staging.multicajadigital.cloud
    description: Staging Environment
  - url: https://tenpo.uat.multicajadigital.cloud
    description: UAT Environment
tags:
  - name: General
    description: Operaciones generales
  - name: Utilities
    description: Operaciones de los convenios de pago de cuenta
  - name: Transactions
    description: Operaciones de transacciones de pago de cuenta
paths:

  /utility-payments/v1/categories:
    get:
      tags: 
        - General
      summary: Lista las categorías de los convenios de pagos de cuenta
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
              example: 
                - id: "100"
                  name: "AGUA"
                - id: "500"
                  name: AUTOPISTAS
                - id: "700"
                  name: RETAIL

  /utility-payments/v1/payment-methods:
    get:
      tags: 
        - General
      summary: Lista los métodos de pago disponibles
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaymentMethod'
              example:
                - "code": "webpay"
                  "name": "Webpay"
                  "private": false
                  "public": true
                - "code": "transferencia"
                  "name": "Transferencia"
                  "private": false
                  "public": true
                - "code": "prepaid"
                  "name": "Prepago"
                  "private": true
                  "public": false

  /utility-payments/v1/utilities:
    get:
      tags: 
        - Utilities
      summary: Lista los convenios de pago de cuenta
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Utility'
              example:
                - "id": 1
                  "name": "Aguas Andinas"
                  "identifier": "NRO CUENTA, CON DIGITO VERIFICADOR"
                  "category_id": "100"
                  "category_name": "AGUA"
                - "id": 2
                  "name": "ESSBIO"
                  "identifier": "NRO SERVICIO, SIN DIGITO VERIFICADOR"
                  "category_id": "100"
                  "category_name": "AGUA"
                - "id": 15
                  "name": "ENEL DISTRIBUCION"
                  "identifier": "NRO CLIENTE, CON DIGITO VERIFICADOR"
                  "category_id": "200"
                  "category_name": "LUZ"
                - "id": 33
                  "name": "Movistar Hogar"
                  "identifier": "NRO TELEFONO, CON CODIGO DE AREA"
                  "category_id": "300"
                  "category_name": "TELEF-TV-INTERNET"
        500:
          description: internal server error

  /utility-payments/v1/utilities/{id}/bills:
    post:
      tags:
        - Utilities
      summary: Obtiene las deudas de un convenio para un determinado identificador
      parameters:
        - in: path
          name: id
          required: true
          description: Id del convenio
          schema:
            type : integer
            format: int64
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UtilityBillRequest'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UtilityBillResponse'
              example:
                - "id": "dd10d4fc-e25e-41be-bde9-e740c7696658"
                  "status": "WAITING"
                  "identifier": "12312312"
                  "amount": 5233
                  "due_date": "No disponible"
                  "description": "Deuda total"
                  "utility":
                      "id": 71
                      "name": "Vespucio Sur"
                      "identifier": "RUT, CON DIGITO VERIFICADOR"
                      "category_id": "500"
                      "category_name": "AUTOPISTAS"
                - "id": "56f31b96-1da2-4372-923d-07b8782f2207"
                  "status": "WAITING"
                  "identifier": "12312312"
                  "amount": 4177
                  "due_date": "No disponible"
                  "description": "Deuda vencida"
                  "utility":
                      "id": 71
                      "name": "Vespucio Sur"
                      "identifier": "RUT, CON DIGITO VERIFICADOR"
                      "category_id": "500"
                      "category_name": "AUTOPISTAS"
        400:
          description: invalid parameteres
        404:
          description: utility not found
        500:
          description: internal server error

  /utility-payments/v1/transactions:
    post:
      tags: 
        - Transactions
      summary: Crea una transacción de pago de cuenta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        400:
          description: invalid parameters
        404:
          description: resource not found
        500:
          description: internal server error

  /utility-payments/v1/transactions/{id}:
    get:
      tags: 
        - Transactions
      summary: Obtiene los detalles de una transacción de pago de cuenta
      parameters: 
        - in: path
          name: id
          required: true
          description: Id de la transacción de pago de cuenta
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        404:
          description: resource not found
        500:
          description: internal server error

  /utility-payments/v1/transactions/{id}/receipt:
    post:
      tags: 
        - Transactions
      summary: Reenvía el comprobante de una transacción de pago de cuenta
      parameters: 
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Id de la transacción de pago de cuenta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReceiptRequest'
      responses:
        200:
          description: successful operation
        400:
          description: invalid parameters
        404:
          description: resource not found
        500:
          description: internal server error
          
components:
  schemas:

    Utility:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Mundo Pacífico
        identifier:
          type: string
          example: "RUT, CON DIGITO VERIFICADOR"
        category_id:
          type: string
          example: 100
        category_name:
          type: string
          example: AGUA
    
    Category:
      type: object
      properties:
        id:
          type: string
          example: 100
        name:
          type: string
          example: AGUA
    
    PaymentMethod:
      type: object
      properties:
        code:
          type: string
          example: webpay
        name:
          type: string
          example: Webpay
        private:
          type: boolean
          example: true
        public:
          type: boolean
          example: false
    
    UtilityBillRequest:
      type: object
      properties:
        identifier:
          type: string
          example: 66823334

    UtilityBillResponse:
      type: object
      properties:
        id:
          type: string
          example: "fb7c3a5f-1db0-4ba0-ab72-a58db5f55f10"
        status:
          type: string
          example: WAITING
        identifier:
          type: string
          example: 66823334
        amount: 
          type: integer
          example: 5467
        due_date:
          type: string
          example: No disponible
        description:
          type: string
          example: Deuda Total
        utility:
          $ref: '#/components/schemas/Utility'
    
    TransactionRequest:
      type: object
      properties:
        bill_id:
          type: string
          example: "fb7c3a5f-1db0-4ba0-ab72-a58db5f55f10"
        email:
          type: string
          example: correo@ejemplo.cl
        payment_method_code:
          type: string
          example: webpay
    
    TransactionResponse:
      type: object
      properties:
        id:
          type: string
          example: 51d95fc6-58e9-4bb0-a622-031cf08edc9c
        status:
          type: string
          example: WAITING
        order:
          type: string
          example: 120190424105826006
        payment_method:
          type: string
          example: WEBPAY
        amount:
          type: integer
          example: 7639
        email:
          type: string
          example: correo@ejemplo.cl
        created:
          type: string
          example: "2019-04-24T10:58:26.140605-04:00"
        updated:
          type: string
          example: "2019-04-24T10:58:26.140605-04:00"
        bill:
          $ref: '#/components/schemas/UtilityBillResponse'
        webpay:
          type: object
          properties:
            id:
              type: string
              example: "1e97647a-e380-4cc8-ba71-6bbd85b5ed07"
            status:
              type: string
              example: WAITING
            url:
              type: string
              example: https://webpay3gint.transbank.cl/webpayserver/initTransaction
            token:
              type: string
              example: e47d8c3c2707730fda36fc15d4418a556e3a1f2bbb7e8cacfff56c0d0bb2d2d0
    
    ReceiptRequest:
      type: object
      properties:
        email:
          type: string
          example: correo@ejemplo.cl
        recaptcha:
          type: string
          example: "03AOLTBLTVBtniCIGwS_N4XFQAQ3d5vXsQJp8kYLRsDcqhBUEf2mh8onvgXDOJ"